name: Code checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Code scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading code_scanner
        run: |
          cd ..
          ls -lah
          mkdir secret_finder
          cd secret_finder
          git clone https://github.com/MiroslavZ/code_scanner.git
          ls -lah
          pwd
      - name: Upgrading pip and installing libraries from requirements.txt
        run: |
          cd ..
          pwd
          ls -lah
          python -m pip install --upgrade pip
          pip install -r secret_finder/code_scanner/requirements.txt
      - name: Installing code_scanner
        run: |
          pip install -e /home/runner/work/${{github.event.repository.name}}/secret_finder/code_scanner
      - name: Scanning the repo
        run: |
          pwd
          ls -lah
          code-scanner --scan-dir /home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/
